Django/demo/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import User
import hashlib

# 注册表单
class RegisterForm(forms.Form):
    email = forms.EmailField(max_length=128,
                             error_messages={'required': u'请输入邮箱', 'invalid': u'邮箱格式不正确', 'max_length': u'邮箱太长了哎'})
    password = forms.CharField(min_length=6, max_length=16,
                               error_messages={'required': u'请输入密码', 'min_length': u'密码长度太短了（至少六位）',
                                               'max_length': u'密码太长了哎'})

    def clean_email(self):
        email = self.cleaned_data['email'].strip()
        is_exist = User.objects.filter(email=email).exists()
        if is_exist:
            raise forms.ValidationError(u'邮箱已经被注册！')
        return email


# 登录表单
class LoginForm(forms.Form):
    email = forms.EmailField(max_length=128,
                             error_messages={'required': u'请输入邮箱', 'invalid': u'邮箱格式不正确', 'max_length': u'邮箱太长了哎'})
    password = forms.CharField(max_length=16, error_messages={'required': u'请输入密码', 'max_length': u'密码太长了哎'})

    def clean_email(self):
        email = self.cleaned_data['email'].strip()
        is_exist = User.objects.filter(email=email).exists()
        if not is_exist:
            raise forms.ValidationError(u'邮箱还没有注册哦！')
        return email

    def clean(self):
        cleaned_data = self.cleaned_data
        email = cleaned_data.get("email", '')
        password = cleaned_data.get("password", '')
        if password and email:
            is_exist = User.objects.filter(email=email.strip(),
                                           password=encode_password(password).strip()).exists()
            if not is_exist:
                raise forms.ValidationError(u"密码错误！")
        return cleaned_data


# 修改密码
class ChangePasswordForm(forms.Form):
    password = forms.CharField(max_length=16, error_messages={'required': u'请输入旧密码', 'max_length': u'密码太长了哎'})
    new_password = forms.CharField(max_length=16, error_messages={'required': u'请输入新密码', 'max_length': u'密码太长了哎'})
    confirm_password = forms.CharField(max_length=16, error_messages={'required': u'请再次输入新密码', 'max_length': u'密码太长了哎'})

    def clean(self):
        cleaned_data = self.cleaned_data
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")
        if confirm_password and new_password:
            if not (confirm_password == new_password):
                raise forms.ValidationError(u"两次输入密码不一致！")
        return cleaned_data

def encode_password(password):
    return hashlib.md5(password).hexdigest()

Django/templates/404.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
</head>

<body>
    <div class="container">
    <div class="span8 offset1" style="margin-top: 30px;">
        <img src="/static/sharehp/img/404.png">
        <div class="alert alert-block" style="margin-left: 35px">
            你访问的页面可能已经被删除！ <a href="/index/"><strong>返回首页</strong></a>
        </div>

    </div>


</div>


</body>
</html>

Django/templates/change_avatar.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>不正常人类研究中心</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link href="/static/css/sharehp.css" rel="stylesheet">
    <link href="/static/css/jquery.fileupload.css" rel="stylesheet">
    <link href="/static/css/jquery.Jcrop.css" rel="stylesheet" type="text/css"/>
    <link href="/static/css/demos.css" rel="stylesheet" type="text/css"/>
</head>
<body>
{% include "header.htm" %}
<div class="container">
    <div class="row">
        <div class="span8">
            <div class="background-wall">
                <div id="upload-avatar">
                    <span class="btn btn-success btn-small fileinput-button">
                        <i class="icon-picture"></i>
                        <span>上传新头像</span>
                        <input id="fileupload" type="file" name="file" data-url="/api/upload_image/" multiple>
                    </span>

                    <div id="error-msg" class="alert alert-error fade in"
                         style="display: none; padding: 2px 35px 2px 8px; margin-bottom: 12px;">
                    </div>

                    <div id="crop-avatar" style="margin-top: 25px">
                        <img class="img-rounded" src="{{ avatar.big|static_url }}">
                        <strong>当前头像</strong>
                    </div>

                </div>
                <div style="margin-bottom: 120px">
                </div>
            </div>
        </div>

        <div class="span4">
            <div class="background-wall">
                <ul class="nav nav-pills nav-stacked">
                    <li class="active">
                        <a href="/account/change_avatar/">我的头像</a>
                    </li>
                    <li><a href="/account/change_password/">修改密码</a></li>
                </ul>
            </div>
        </div>
    </div>

    <br>
    <br>
    <br>
    <br>
</div>
<script src="http://cdn.staticfile.org/jquery/1.7.2/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="/static/sharehp/js/upload/vendor/jquery.ui.widget.js"></script>
<script src="/static/sharehp/js/upload/jquery.iframe-transport.js"></script>
<script src="/static/sharehp/js/upload/jquery.fileupload.js"></script>
<script src="/static/sharehp/js/jquery.Jcrop.min.js"></script>
<script type="text/javascript">
    var crop_x, crop_y, crop_width, crop_height;
    var attach_id = '';

    function init_global_var() {
        crop_x = 0;
        crop_y = 0;
        crop_width = 100;
        crop_height = 100;
        attach_id = '';
    }

    function init_jcrop(width, height) {
        // Create variables (in this scope) to hold the API and image size
        var jcrop_api, boundx, boundy;

        $('#target').Jcrop({
            onChange: updatePreview,
            onSelect: updatePreview,
            aspectRatio: 1,
            minSize: [100, 100], // image size at least 100*100
            trueSize: [width, height]
        }, function () {
            // Use the API to get the real image size
            var bounds = this.getBounds();
            boundx = bounds[0];
            boundy = bounds[1];
            // Store the API in the jcrop_api variable
            jcrop_api = this;
            jcrop_api.setSelect([0, 0, 100, 100]);
        });

        function updatePreview(c) {
            if (parseInt(c.w) > 0) {
                crop_x = c.x;
                crop_y = c.y;
                crop_width = c.w;
                crop_height = c.h;

                var rx = 100 / c.w;
                var ry = 100 / c.h;

                $('#preview').css({
                    width: Math.round(rx * boundx) + 'px',
                    height: Math.round(ry * boundy) + 'px',
                    marginLeft: '-' + Math.round(rx * c.x) + 'px',
                    marginTop: '-' + Math.round(ry * c.y) + 'px'
                });
            }
        }
    }

    $(function () {
        $('#fileupload').fileupload({
            dataType: 'json',
            add: function (e, data) {
                $('#crop-avatar').unbind().remove();
                init_global_var();
                data.submit();
            },
            done: function (e, result) {
                result = JSON.parse(JSON.stringify(result.result));
                // 图片上传成功
                if (result.success == 0) {
                    var img_src = '/static/sharehp/tmp/' + result.data.src;
                    var img_width = result.data.width;
                    var img_height = result.data.height;
                    // 附件ID
                    attach_id = result.data.src

                    $('#upload-avatar').append(crop_avatar_area(img_src, img_width, img_height));
                    init_jcrop(img_width, img_height);
                    $('#submit-avatar').bind('click', function () {
                        // check post param FIXME

                        // loading status ...
                        $('#submit-avatar').button('loading');
                        $('#submit-loading').css("display", "inline");

                        $.post('/account/change_avatar/',
                                {
                                    attach: attach_id,
                                    crop_x: crop_x,
                                    crop_y: crop_y,
                                    crop_width: crop_width,
                                    crop_height: crop_height
                                },
                                function (result, status) {
                                    result = JSON.parse(result);
                                    if (result.success == 0) {
                                        var src = result.data.src;
                                        $('#upload-avatar').html(change_avatar_success(src));

                                    } else {
                                        setErrorMsg(result.error_msg);
                                    }

                                }).fail(function () {
                                    setErrorMsg('尼码， 服务器出现异常了，管理员赶紧过来看看！');
                                }).always(function () {
                                    // reset status
                                    $('#submit-avatar').button('reset');
                                    $('#submit-loading').css("display", "none");
                                });
                    });
                    $('#crop-avatar').css('display', 'block');
                } else {
                    setErrorMsg(result.error_msg);
                }
            }
        });
    });


    function crop_avatar_area(src, width, height) {
        var preview_image = '<img src=' + src + ' id="preview"/>';
        var target_image = '<img src=' + src + ' id="target"/>';
        if (parseInt(width) > 300) {
            target_image = '<img style="width: 300px" src=' + src + ' id="target"/>';
        }
        return '<div id="crop-avatar" class="article clearfix" style="display: none"><h4>请拖动矩形框选择裁剪区域</h4><table><tr><td>' + target_image + '</td><td>' + '<img width="40" src="http://res.baoz.cn/imgs/arrow-1.png"></td><td><div style="margin-left:8px;width:100px;height:100px;overflow:hidden;">' +
                preview_image + '</div></td></tr></table><br><button id="submit-avatar" class="btn btn-large btn-primary" type="button" data-loading-text="正在提交">确定</button><img id="submit-loading" style="display:none;padding-top:5px"  src="http://sharehp.qiniudn.com/share/mini_loading.gif"></div>'


    }

    function change_avatar_success(image_src) {
        return '<div class="alert alert-success"><h5>修改头像成功!</h5></div>'
    }

    function setErrorMsg(msg) {
        $('#error-msg').text(msg).css('display', 'block');
    }
</script>
</body>
</html>

Django/templates/change_password.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>不正常人类研究中心</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link href="/static/css/sharehp.css" rel="stylesheet">
</head>
<body>
{% include "header.htm" %}
<div class="container">
    <div class="row">
        <div class="span8">
            <div class="background-wall">
                {% if success %}
                    <div class="alert alert-success">
                        <h5>修改密码成功!</h5>
                    </div>
                {% else %}
                    <div class="form-change-password">
                        <form action="/account/change_password/" method="post">
                            <span class="error">{{ form.non_field_errors }}</span>
                            <span class="error">{{ form.password.errors }}</span>
                            <input id="id_password" name="password" type="password" class="input-block-level"
                                   placeholder="旧密码" value="{{ form.password.value }}">
                            <span class="error">{{ form.new_password.errors }}</span>
                            <input id="id_new_password" name="new_password" type="password" class="input-block-level"
                                   placeholder="新密码" value="{{ form.new_password.value }}">
                            <span class="error">{{ form.confirm_password.errors }}</span>
                            <input id="id_confirm_password" name="confirm_password" type="password"
                                   class="input-block-level"
                                   placeholder="确认新密码" value="{{ form.confrim_password.value }}">
                            <button class="btn input-block-level btn-primary" type="submit">确定</button>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="span4">
            <div class="background-wall">
                <ul class="nav nav-pills nav-stacked">
                    <li>
                        <a href="/account/change_avatar/">我的头像</a>
                    </li>
                    <li class="active">
                        <a href="/account/change_password/">修改密码</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <br>
    <br>
    <br>
    <br>
</div>
<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
</body>
</html>

Django/templates/contact_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="/contact/" method="post">
        <p>Subject: <input type="text" name="subject"> value="{{subject}}"</p>
        <p>Your e-mail (optional): <input type="text" name="email"> value="{{ email }}"</p>
        <p>Message: <textarea name="message" rows="10" cols="50">{{ message }}</textarea></p>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

Django/templates/current_datetime.html
<html><body>It is now {{ current_date }}.</body></html>

Django/templates/date.html
<html><body>It is now 8pm.</body></html>

Django/templates/footer.htm
<footer class="footer">
    <div class="container">
        <p class="pull-right"><a href="#" target="_self">回到顶部</a></p>
        <p>Powered by Django © 2014 </p>
    </div>
</footer>

Django/templates/header.htm
<!-- 导航栏 -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner ">
        <div class="container">
            <ul class="nav pull-right">
                {% if request.xmanuser.login %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            {{ request.xmanuser.nickname }}
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/account/change_avatar/">帐号设置</a></li>
                            <li class="divider"></li>
                            <li><a href="/loginout/">退出</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>


<br>

Django/templates/index.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>Citrix China Demo Center</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link href="/static/css/sharehp.css" rel="stylesheet" media="screen">
</head>

<body>

<header class="jumbotron subhead">
    <div class="container">
        <h2 class="text-center">Citrix China Demo Center</h2>
    </div>
</header>

<br>



<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
</body>
</html>

Django/templates/login.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>Citrix China Demo Center</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"
          media="screen">
    <link href="/static/css/sharehp.css" rel="stylesheet" media="screen">
</head>

<body>

<header class="jumbotron subhead">
    <div class="container">
        <h2 class="text-center">Citrix China Demo Center</h2>
    </div>
</header>

<br>

<div class="container">
    <div class="form-signin-register">
        <form action="{{ login_action_url }}" method="post">
            <div class="form-title">
                <h4>登陆帐号</h4>
            </div>
            <span class="error">{{ form.non_field_errors }}</span>
            <span class="error">{{ form.email.errors }}</span>
            <input id="id_email" name="email" type="text" class="input-block-level" placeholder="邮箱"
                   value="{{ form.email.value }}">
            <span class="error">{{ form.password.errors }}</span>
            <input id="id_password" name="password" type="password" class="input-block-level" placeholder="密码"
                   value="{{ form.password.value }}">
            <button class="btn input-block-level btn-primary" type="submit">登陆</button>
        </form>
        <a href="/register/">没有帐号？立即注册</a>
    </div>
</div>

<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
</body>
</html>

Django/templates/option.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>Citrix China Demo Center</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/css/sharehp.css" rel="stylesheet" media="screen">
    
</head>

<body>

<header class="jumbotron subhead">
    <div class="container">
        <h2 class="text-center">Citrix China Demo Center</h2>
    </div>
</header>

<body>

<div class="container">
    <div class="form-laborder">
	<form action="/orderlab/" method="POST">
	    <br>
		<select name="labtype">  
		  	<option value="1">Please select a course</option>  
		  	<option value="2">XenServer</option>  
		  	<option value="3">XenDesktop</option>  
		  	<option value="4">XenApp</option>
		  	<option value="5">CloudPlatform</option>
		</select>  

		<select name="labdays">  
		  	<option value="1">1 Day</option>  
		  	<option value="3">3 Days</option>  
		  	<option value="7">7 Days</option>  
		  	<option value="15">15 Days</option>
		  	<option value="30">30 Days</option>
		</select>  
	    <br />
	    <br>	
		<input type="radio" name="labtime" value="1" checked="checked" />Immediate provisioning
	    <br />
		<input type="radio" name="labtime" value="2" />Schedule a lab
		<input type="text" name="input1" onclick="new Calendar().show(this);" />
		<select name="hour">  
			<option value="0">0</option>
		  	<option value="1">1</option>  
		  	<option value="2">2</option>  
		  	<option value="3">3</option>  
		  	<option value="4">4</option>
		  	<option value="5">5</option>
		  	<option value="6">6</option>
			<option value="7">7</option>
			<option value="8">8</option>
			<option value="9">9</option>
			<option value="10">10</option>
			<option value="11">11</option>
			<option value="12">12</option>
		</select>  
		<select name="minute">  
		  	<option value="1">00</option>  
		  	<option value="2">15</option>  
		  	<option value="3">30</option>  
		  	<option value="4">45</option>
		</select>  
		<select name="noon">  
		  	<option value="1">AM</option>  
		  	<option value="2">PM</option>  
		</select>  
		<button class="btn input-block-level btn-primary" type="submit">ok</button>
	 </form>
</body>
</html>

Django/templates/ordersuccess.htm
<html>
<head>
</head>
<body>
Order success!
</body>
</html>

Django/templates/register.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>Citrix China Demo Center</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/css/sharehp.css" rel="stylesheet" media="screen">
</head>

<body>

<header class="jumbotron subhead">
    <div class="container">
        <h2 class="text-center">Citrix China Demo Center</h2>
    </div>
</header>

<br>

<div class="container">
    <div class="form-signin-register">
        <form action="{{ register_action_url }}" method="post">
            <div class="form-title">
                <h4>注册帐号</h4>
            </div>
            <span class="error">{{ form.email.errors }}</span>
            <input id="id_email" name="email" type="text" class="input-block-level" placeholder="邮箱"
                   value="{{ form.email.value }}">
            <span class="error">{{ form.password.errors }}</span>
            <input id="id_password" name="password" type="password" class="input-block-level" placeholder="密码（6-16位）"
                   value="{{ form.password.value }}">
            <button class="btn input-block-level btn-primary" type="submit">注册</button>
        </form>
        <a href="/login/">已经有帐号？立即登录</a>
    </div>
</div>

<script src="http://cdn.staticfile.org/jquery/2.0.0/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
</body>
</html>

Django/templates/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>